### ISSUE TITLE
fins that have been rescaled seem to not save their proper postions it will move it like inside the part its supposed to be at tached to

### ISSUE THREAD

**Issue by falcon470** [TweakScale/TweakScale#295]
fins that have been rescaled seem to not save their proper postions it will move it like inside the part its supposed to be attached to, 
it will put the fin inside the booster for example instead of on the side of it, not how to is in editor, its also possible its one of my other mods so feel free to close this issue if you cnat reroduce parts i was rescaling are the stock fins, not game breaking for me as i have other mods such as the procedural wings, not unlocked yet in my career, but if other people are experiancing it you might want to look into it.

**Comment by Lisias** [comment]
hi @falcon470 .

> fins that have been rescaled seem to not save their proper positions it will move it like inside the part its supposed to be attached to, it will put the fin inside the booster for example instead of on the side of it

On an initial guess, I'm betting on an unfortunate interaction with some other add'on.

At every release, I do a smoke test by loading an Aeroequs, "chain scale" the Mk1 capsule (and, so, everything scales together) to 1.8 or 2.5m and fire it up.

Such an obvious problem on a fin would be immediately detected.

Anyway, I redid the test but shoving different Stock fins everywhere (including the boosters) to see what I get:

![screenshot6](https://user-images.githubusercontent.com/64334/229370399-d78704c7-18f6-4679-87ca-ca418fb9bbac.png)

![screenshot7](https://user-images.githubusercontent.com/64334/229370432-1445a898-e89d-4055-b2f9-375ae4b3352b.png)

![screenshot8](https://user-images.githubusercontent.com/64334/229370446-895b5bc4-bac1-4e9a-87c1-54f9c44132c5.png)

![screenshot9](https://user-images.githubusercontent.com/64334/229370457-6b0392c2-3387-456e-b95a-75ccb5d3e4ec.png)

![screenshot10](https://user-images.githubusercontent.com/64334/229370461-ce4692a2-9e89-451b-bf7c-d37a1a59a702.png)

As you can see, everything is working **flawlessly**.

I need your KSP.log and a minimal sample craft file where he problem happens. It's **DEFINITIVELY** something in your rig misbehaving, and the evidences above proves that it's not TweakScale (neither Recall)

**Comment by Lisias** [comment]
Closing as I didn't got any feedback from the user.
