### ISSUE TITLE
Houston, We have a Problem.

### ISSUE THREAD

**Issue by Kyleo3345** [TweakScale/TweakScale#341]
I have an issue with the Tweakscale.

KSP version being use is 1.12.5

Image of what the Issue:
![image](https://github.com/user-attachments/assets/862595fb-6023-45d2-a342-c093dda3e393)

Log:
[ModuleManager.log](https://github.com/user-attachments/files/17877069/ModuleManager.log)

Can you help me out with this?

**Comment by Lisias** [comment]
Hi, @Kyleo3345 .

I need the `KSP.log` to check what's happening. What you got is probably a Reflection bug on KSP, and I need to check `KSP.log` to see what's missing and then solve the problem.

**Comment by Kyleo3345** [comment]
Here's the log:
[KSP.log](https://github.com/user-attachments/files/17894731/KSP.log)

**Comment by Lisias** [comment]
> Here's the log: [KSP.log](https://github.com/user-attachments/files/17894731/KSP.log)

Yep... 

```
[WRN 16:32:48.770] AssemblyLoader: Assembly 'BetterTimeWarpContinued' has not met dependency 'ClickThroughBlocker' V1.0.0
[WRN 16:32:48.771] AssemblyLoader: Assembly 'BetterTimeWarpContinued' has not met dependency 'ToolbarController' V1.0.0
[WRN 16:32:48.771] AssemblyLoader: Assembly 'BetterTimeWarpContinued' is missing 2 dependencies[WRN 16:32:48.771] AssemblyLoader: Assembly 'KerbalKonstructs' has not met dependency 'CustomPreLaunchChecks' V1.0.0
[WRN 16:32:48.771] AssemblyLoader: Assembly 'KerbalKonstructs' is missing 1 dependencies
[WRN 16:32:48.771] AssemblyLoader: Assembly 'Kopernicus' has not met dependency 'ModularFlightIntegrator' V1.0.0
[WRN 16:32:48.771] AssemblyLoader: Assembly 'Kopernicus' has not met dependency '0Harmony' V0.0.0
[WRN 16:32:48.771] AssemblyLoader: Assembly 'Kopernicus' is missing 2 dependencies
```

Remove `BetterTimeWarpContinued`, `KerbalKonstructs` and `Kopernicus`. This should "fix" your rig. If not, send me the a new `KSP.log` so I can see what else borked now.

if everything loads fine, then you need to reinstall these back, but with the dependencies this time.

To install Better Time Warp, you need to install also:

* https://forum.kerbalspaceprogram.com/topic/170747-112x-click-through-blocker-new-
dependency/
* https://forum.kerbalspaceprogram.com/topic/169509-112x-toolbar-controller-for-modders/

To install KerbalKonstructs, you need to install also:

* https://forum.kerbalspaceprogram.com/topic/187525-18x-customprelaunchchecks/

To install Kopernicus, you need to install:

* https://forum.kerbalspaceprogram.com/topic/106369-19-modularflightintegrator-127-19-october-2019/
* https://github.com/KSPModdingLibs/HarmonyKSP/releases

**Comment by Kyleo3345** [comment]
Ok. I'll let you know.

**Comment by Lisias** [comment]
@Kyleo3345 

Now it's parallax the one complaning

```
[ERR 13:58:54.347] AssemblyLoader: Exception loading 'Parallax': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLo
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <4b449f2841f84227adfaad3149c8fdba>:0

Additional information about this exception:

 System.IO.FileNotFoundException: Could not load file or assembly 'Kopernicus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Kopernicus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

Remove it too, and restart from scratch as explained on https://github.com/TweakScale/TweakScale/issues/341#issuecomment-2496515334

**Comment by Kyleo3345** [comment]
No "Houston, We have a Problem." Popup.

**Comment by Lisias** [comment]
@Kyleo3345 

Great! Now install the add'ons you want one by one, making sure you are installing all their dependencies.

Don't install all of them at once, choose one, make it work, and then install the another.

This way any problem will be easily handled.

**Comment by Kyleo3345** [comment]
Thanks for the help.
